### ISSUE TITLE
Support for version 12.0?

### ISSUE THREAD

**Issue by danielmmmm** [Rinnegatamante/not_a_hero-vita#1]
Would it be possible ... or useful ... to make this port compatible with v12.0 of the game?

Unfortunately, since the game is not available on Google Play any more, I don't know what changed from v1.0 to v12.0 🙁

**Comment by Rinnegatamante** [comment]
![immagine](https://github.com/Rinnegatamante/not_a_hero-vita/assets/9152710/b7fd2931-ff91-4f31-ac15-d1b705b135b2)

**Comment by danielmmmm** [comment]
Hm, when I use the libs and assets from v12.0, the game crashes with "Unknown symbol pthread_setname_np (0x9861ef3c)".

The working v1.0 of the game is an apk that's easy to extract. The newer v12.0 is split into an apk, containing the libs, and an obb (fat32 image, not zip), containing the assets.

Do you have a checksum of the apk your port is working with? On reddit, you can find an apk with CRC32 of D7070CE3, which is v1.0. APK Easy Tool shows version code "1" and target SDK "12". Maybe that caused a confusion of game version v1.0 with v12.0?
